---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: test
spec:
  ports:
    - name: test
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: test
  type: ClusterIP
